# Generated by Django 3.1.7 on 2021-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_time', models.DateTimeField(auto_created=True)),
                ('address', models.EmailField(max_length=200)),
                ('text', models.TextField()),
                ('delay', models.IntegerField(default=0)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
