# Generated by Django 3.1.7 on 2021-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='delay',
            new_name='timeout',
        ),
        migrations.AlterField(
            model_name='mail',
            name='dispatch_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
