# Generated by Django 3.1.7 on 2021-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0002_auto_20210301_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
