# Generated by Django 3.1.7 on 2021-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_mail_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
